name: bide_et_musique
description: Écouter et consulter la web radio 'Bide et Musique'

version: 3.3.5+44

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.16.1
  cached_network_image: ^2.5.0
  diacritic: ^0.1.1
  flutter_html: ^1.1.0
  html: ^0.14.0+4
  http: ^0.12.2
  just_audio: ^0.6.5
  package_info: ^0.4.3+2
  page_indicator: ^0.3.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  uni_links: ^0.4.0
  url_launcher: ^5.7.10
  xml: ^4.5.1
  flutter_launcher_icons: ^0.8.1
  flutter_statusbarcolor: ^0.2.3

flutter_icons:
  android: false
  ios: true
  image_path: "assets/bm_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png